openapi: 3.0.0
info:
  title: MijnApp
  description: Deze documentatie beschrijft de generieke MijnApp api.
  version: 0.1.0

servers: 
  - url: accp.example.com/api/v1
    description: Acceptatie domein

paths:
  /personen/{bsn}:
    get:
      summary: Persoondetails
      parameters:
        - in: path
          name: bsn
          schema:
            type: string
          required: true
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
                  
  /personen/{bsn}/contracten:
    get:
      summary: Lijst met contracten
      parameters:
        - in: path
          name: bsn
          schema:
            type: string
          required: true
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
  
  /personen/{bsn}/contracten/{id}:
    get:
      summary: Contractdetails
      parameters:
        - in: path
          name: bsn
          schema:
            type: string
          required: true
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: Contractidentificatie
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
                  
  /personen/{bsn}/logregels:
    get:
      summary: AVG logregels
      parameters:
        - in: path
          name: bsn
          schema:
            type: string
          required: true
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
  
  /personen/{bsn}/logregels/{id}:
    get:
      summary: AVG logregeldetails
      parameters:
        - in: path
          name: bsn
          schema:
            type: string
          required: true
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: Contractidentificatie
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string

# 1) Define the security scheme type (HTTP bearer)
components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT    # optional, arbitrary value for documentation purposes
# 2) Apply the security globally to all operations
security:
  - bearerAuth: []         # use the same name as above